name: Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install Deps
        shell: bash -l {0}
        run: |
          conda install -c conda-forge scikit-learn plotly seaborn pandas numpy matplotlib ipywidgets fbprophet
      - name: Setup Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      # - name: Get Latest Data
      #   shell: bash -l {0}
      #   run: ./update.sh
      - name: Get Latest Data
        shell: bash -l {0}
        run: python ./scripts/covid_19_data.py


# https://github.com/ad-m/github-push-action
        

